name: Send HF Daily Papers to Discord

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 00:00 UTC (한국시간 09:00)
  workflow_dispatch:      # 수동 실행도 가능

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python main.py
